[package]
name = "uni-v4-hook-address-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
clap = { version = "4.5.21", features = ["derive"] }
spinners = "4.1.1"
alloy-primitives = "0.8.18"